name: CI

on:
  push:
    branches:
      - '*'
      - '!master'

env:
  PACKAGE_NAME: aws-iot-securetunneling-localproxy

jobs:
#   osx:
#     runs-on: macos-latest
#     steps:
#     - name: Install brew dependencies
#       run: |
#         brew install openssl zlib cmake wget git
#     - uses: actions/checkout@v2
#       name: 'Checkout'
#     - name: install boost
#       working-directory: ${{ github.workspace }}
#       run: |
#         wget https://localproxy-binaries.s3-us-west-2.amazonaws.com/osx/boost_169.zip
#         unzip boost_169.zip -d boost_169 || :
#         cd boost_169
#         chmod +x b2
#         ./b2 install toolset=clang
#     - name: install protobuf
#       working-directory: ${{ github.workspace }}
#       run: |
#         wget https://github.com/protocolbuffers/protobuf/releases/download/v3.6.1/protobuf-all-3.6.1.tar.gz -O /tmp/protobuf-all-3.6.1.tar.gz
#         tar xzvf /tmp/protobuf-all-3.6.1.tar.gz
#         cd protobuf-3.6.1
#         mkdir build_make
#         cd build_make
#         cmake ../cmake
#         make
#         make install
#     - name: install Catch2
#       working-directory: ${{ github.workspace }}
#       run: |
#         git clone https://github.com/catchorg/Catch2.git
#         cd Catch2
#         mkdir build
#         cd build
#         cmake ../
#         make
#         make install
#     - name: Building ${{ env.PACKAGE_NAME }}
#       working-directory: ${{ github.workspace }}
#       run: |
#         mkdir build
#         cd build
#         cmake .. -DOPENSSL_ROOT_DIR=/usr/local/Cellar/openssl@1.1/1.1.1g/ -DOPENSSL_LIBRARIES=/usr/local/Cellar/openssl@1.1/1.1.1g/lib/
#         make
#   ubuntu:
#     runs-on: ubuntu-18.04
#     steps:
#     - name: Install apt-get dependencies
#       run: |
#         sudo apt-get install -y build-essential git python3-dev
#         sudo apt-get install -y wget tar zlibc libssl-dev openssl cmake python-dev
#         sudo apt-get clean -y
#     - uses: actions/checkout@v2
#       name: 'Checkout'
#     - name: install boost
#       working-directory: ${{ github.workspace }}
#       run: |
#         wget https://dl.bintray.com/boostorg/release/1.69.0/source/boost_1_69_0.tar.gz -O /tmp/boost.tar.gz
#         tar xzvf /tmp/boost.tar.gz
#         cd boost_1_69_0
#         ./bootstrap.sh
#         sudo ./b2 install
#     - name: install protobuf
#       working-directory: ${{ github.workspace }}
#       run: |
#         wget https://github.com/protocolbuffers/protobuf/releases/download/v3.6.1/protobuf-all-3.6.1.tar.gz -O /tmp/protobuf-all-3.6.1.tar.gz
#         tar xzvf /tmp/protobuf-all-3.6.1.tar.gz
#         cd protobuf-3.6.1
#         mkdir build_make
#         cd build_make
#         cmake ../cmake
#         make
#         sudo make install
#     - name: install Catch2
#       working-directory: ${{ github.workspace }}
#       run: |
#         git clone https://github.com/catchorg/Catch2.git
#         cd Catch2
#         mkdir build
#         cd build
#         cmake ../
#         make
#         sudo make install
#     - name: Building ${{ env.PACKAGE_NAME }}
#       working-directory: ${{ github.workspace }}
#       run: |
#         mkdir build
#         cd build
#         cmake .. -DOPENSSL_ROOT_DIR=/usr/local/Cellar/openssl@1.1/1.1.1g/ -DOPENSSL_LIBRARIES=/usr/local/Cellar/openssl@1.1/1.1.1g/lib/
#         make
  windows:
    runs-on: windows-2019
    steps:
      - uses: ilammy/msvc-dev-cmd@v1
      - name: 'Install Catch2'
        run: |
          git clone https://github.com/catchorg/Catch2.git
          cd Catch2
          mkdir build
          cd build
          cmake -DBUILD_TESTING=OFF -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release ../
          nmake
          nmake install
          ls  C:\Program Files (x86)\
          ls C:\Program Files\
      - name: 'Install ZLIP'
        run: |
          git clone -b v1.2.8 https://github.com/madler/zlib.git
          cd zlib
          mkdir build
          cd build
          cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release ../
          nmake
          nmake install
          $env:Path += ";C:\Program Files (x86)\zlib\bin"
      - name: "Install Boost"
        run: |
          Invoke-WebRequest "https://dl.bintray.com/boostorg/release/1.69.0/source/boost_1_69_0.zip" -OutFile "boost_1_69_0.zip"
          Expand-Archive "boost_1_69_0.zip" -Force
          cd .\boost_1_69_0\boost_1_69_0\
          .\bootstrap.bat
          .\b2 install
      - name: "Install Protobuf"
        run: |
          Invoke-WebRequest "https://github.com/protocolbuffers/protobuf/releases/download/v3.6.1/protobuf-all-3.6.1.zip" -OutFile "protobuf-all-3.6.1.zip"
          Expand-Archive protobuf-all-3.6.1.zip
          cd .\protobuf-all-3.6.1\protobuf-3.6.1\cmake\
          mkdir build
          cd build
          cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release -Dprotobuf_MSVC_STATIC_RUNTIME=OFF ../
          nmake
          nmake install
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: "Build Local Proxy"
        working-directory: ${{ github.workspace }}
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_PREFIX_PATH="C:\Boost;C:\Program Files (x86)\Catch2;C:\Program Files (x86)\protobuf;C:\Program Files\OpenSSL" -G "Visual Studio 16 2019" ..\
          ls
          msbuild localproxy.vcxproj -p:Configuration=Release
          ls bin/Release
