name: CI

on:
  push:
    branches:
      - '*'
      - '!master'

env:
  PACKAGE_NAME: aws-iot-securetunneling-localproxy

jobs:
  osx:
    runs-on: macos-latest
    steps:
    - name: Install brew dependencies
      run: |
        brew install openssl zlib cmake wget git
    - uses: actions/checkout@v2
      name: 'Checkout'
    - name: install boost
      working-directory: ${{ github.workspace }}
      run: |
        wget https://localproxy-binaries.s3.us-west-2.amazonaws.com/osx/boost_169.zip?response-content-disposition=attachment&X-Amz-Security-Token=IQoJb3JpZ2luX2VjECAaCXVzLXdlc3QtMiJIMEYCIQCykfllx9AA4YSLNOnkLjp5n8zd6q%2BkZ5vxdeJDWyCmewIhAINnXA4orrR7rSXjlAXF%2BYJoorwcGCEw0gKJPA3HsuFSKogCCKn%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEQABoMOTY1NDUyMjQ3NTQ1IgyKoYf9W3NsxHV58%2B8q3AHOskXTputs0xPuHGX%2FmPSRVH0mSsk4clH8vZON5wjNzZ0CjKsspWaaliOZwoj5qAh3mhCaiUUzPAE%2FJvjJmWCyvGA7fudL7IqO5Pz%2F0WI18yoZNNJybxKL87zpLQBJVLpuO737b%2BngVwZOjwEWuyjtkQ%2FyjqgJtUdsCZh0Q%2Bidn6ciHVM2MvAu2jxHwkDMjWhYjaw5ADrThDsgHjYn%2BP9CBP67idfD%2Fi8mEVRrKQMpztkZacG%2BFCa7NscDpMPSuHtpFUbGpGR0EU2pWfAfUJbwD0mHrAgt1g7L%2FuxNMP6Q0%2FcFOsgCrKINJzxFDfdAsGsb1DsfrOsJKeccQsaj1ZrRPYIARC1HbEbzmHegC5UVqrIcIYgaokSD1R3Ys5L%2B3%2FLqmsSBhs6rQrNUh5285tEN7%2FslbxO1By21Buf1HQdgxiHmUYihssnIXnl3u0IvV6X7wnyUiW9cEa%2FD09llQ42Jzx52h%2BufVR%2FWFR7z01d5OIRQYMlLh2QnCCuq%2F03C5OSgpkJfs7jE9cnqx1ZLSTlehSgtz7F7PdsAnZYr3nAxfgVcHKIJWKTyZ9kJyj0hu585E8IaOk96mnymjYbdnKLQm260rGYaDAS6XEpNzrmuoZUUye5hxlbPNbdfrJ3vSrzTsuPS8W8y8SvjobCG7a6ynOC7cBF7mUAAfrj5i0TjuqFvDOoS2GwXw4Di37jCwdkEmRjWI4jlDoGGuN5kkwseEAlGft0Csd6NZJhRFw%3D%3D&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20200625T155415Z&X-Amz-SignedHeaders=host&X-Amz-Expires=300&X-Amz-Credential=ASIA6BSLQGH46SCSCN4Y%2F20200625%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Signature=ae9836e7a9e36f1523fd09658f02fb9aef1c68baa1814a105c044ee655e1880a
        unzip boost_169.zip -d boost_169
        cd boost_1_69_0
        ./b2 install toolset=clang
    - name: install protobuf
      working-directory: ${{ github.workspace }}
      run: |
        wget https://localproxy-binaries.s3.us-west-2.amazonaws.com/osx/protobuf-3.6.1.zip?response-content-disposition=attachment&X-Amz-Security-Token=IQoJb3JpZ2luX2VjECAaCXVzLXdlc3QtMiJIMEYCIQCykfllx9AA4YSLNOnkLjp5n8zd6q%2BkZ5vxdeJDWyCmewIhAINnXA4orrR7rSXjlAXF%2BYJoorwcGCEw0gKJPA3HsuFSKogCCKn%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEQABoMOTY1NDUyMjQ3NTQ1IgyKoYf9W3NsxHV58%2B8q3AHOskXTputs0xPuHGX%2FmPSRVH0mSsk4clH8vZON5wjNzZ0CjKsspWaaliOZwoj5qAh3mhCaiUUzPAE%2FJvjJmWCyvGA7fudL7IqO5Pz%2F0WI18yoZNNJybxKL87zpLQBJVLpuO737b%2BngVwZOjwEWuyjtkQ%2FyjqgJtUdsCZh0Q%2Bidn6ciHVM2MvAu2jxHwkDMjWhYjaw5ADrThDsgHjYn%2BP9CBP67idfD%2Fi8mEVRrKQMpztkZacG%2BFCa7NscDpMPSuHtpFUbGpGR0EU2pWfAfUJbwD0mHrAgt1g7L%2FuxNMP6Q0%2FcFOsgCrKINJzxFDfdAsGsb1DsfrOsJKeccQsaj1ZrRPYIARC1HbEbzmHegC5UVqrIcIYgaokSD1R3Ys5L%2B3%2FLqmsSBhs6rQrNUh5285tEN7%2FslbxO1By21Buf1HQdgxiHmUYihssnIXnl3u0IvV6X7wnyUiW9cEa%2FD09llQ42Jzx52h%2BufVR%2FWFR7z01d5OIRQYMlLh2QnCCuq%2F03C5OSgpkJfs7jE9cnqx1ZLSTlehSgtz7F7PdsAnZYr3nAxfgVcHKIJWKTyZ9kJyj0hu585E8IaOk96mnymjYbdnKLQm260rGYaDAS6XEpNzrmuoZUUye5hxlbPNbdfrJ3vSrzTsuPS8W8y8SvjobCG7a6ynOC7cBF7mUAAfrj5i0TjuqFvDOoS2GwXw4Di37jCwdkEmRjWI4jlDoGGuN5kkwseEAlGft0Csd6NZJhRFw%3D%3D&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20200625T155441Z&X-Amz-SignedHeaders=host&X-Amz-Expires=300&X-Amz-Credential=ASIA6BSLQGH46SCSCN4Y%2F20200625%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Signature=0b54c2edd8a6715d484df4c217754b6f54b9d98dc132dca041a9ba0d04be956d
        unzip protobuf-3.6.1.zip -d protobuf-3.6.1
        cd protobuf-3.6.1/build_make
        make install
    - name: install Catch2
      working-directory: ${{ github.workspace }}
      run: |
        git clone https://github.com/catchorg/Catch2.git
        cd Catch2
        mkdir build
        cd build
        cmake ../
        make
        make install
    - name: Building ${{ env.PACKAGE_NAME }}
      working-directory: ${{ github.workspace }}
      run: |
        mkdir build
        cd build
        cmake .. -DOPENSSL_ROOT_DIR=/usr/local/Cellar/openssl@1.1/1.1.1g/ -DOPENSSL_LIBRARIES=/usr/local/Cellar/openssl@1.1/1.1.1g/lib/
        make
    - uses: actions/upload-artifact@v1
      with:
        name: localproxy
        path: ${{ github.workspace }}/build/bin
      name: 'Upload Package'