name: CI

on:
  push:
    branches:
      - '*'
      - '!master'

env:
  PACKAGE_NAME: aws-iot-securetunneling-localproxy

jobs:
  osx:
    runs-on: macos-latest
    steps:
    - name: Install brew dependencies
      run: |
        brew install openssl zlib cmake wget git
    - name: install protobuf
      working-directory: ${{ github.workspace }}
      run: |
        wget https://localproxy-binaries.s3-us-west-2.amazonaws.com/osx/protobuf-3.6.1.zip
        unzip protobuf-3.6.1.zip -d protobuf-3.6.1 || :
    - uses: actions/checkout@v2
      name: 'Checkout'
    - name: install boost
      working-directory: ${{ github.workspace }}
      run: |
        wget https://localproxy-binaries.s3-us-west-2.amazonaws.com/osx/boost_169.zip
        unzip boost_169.zip -d boost_169 || :
        cd boost_169
        chmod +x b2
        ./b2 install toolset=clang
    - name: install Catch2
      working-directory: ${{ github.workspace }}
      run: |
        git clone https://github.com/catchorg/Catch2.git
        cd Catch2
        mkdir build
        cd build
        cmake ../
        make
        make install
    - name: Building ${{ env.PACKAGE_NAME }}
      working-directory: ${{ github.workspace }}
      run: |
        mkdir build
        cd build
        cmake .. -DOPENSSL_ROOT_DIR=/usr/local/Cellar/openssl@1.1/1.1.1g/ -DOPENSSL_LIBRARIES=/usr/local/Cellar/openssl@1.1/1.1.1g/lib/ -DProtobuf_LIBRARIES=${{ github.workspace }}/protobuf-3.6.1/usr/local/lib -DProtobuf_INCLUDE_DIR=${{ github.workspace }}/protobuf-3.6.1/usr/local/include/
        make
    - uses: actions/upload-artifact@v1
      with:
        name: localproxy
        path: ${{ github.workspace }}/build/bin
      name: 'Upload Package'
